version: '3.8'
services:
    bot:
        container_name: bot
        build:
            dockerfile: ./bot/Dockerfile
            target: prod
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        ports:
            - "8001:8001"
        env_file:
            - .env
        restart: on-failure
        command: node main.js

    api:
        container_name: api
        build:
            dockerfile: ./api/Dockerfile
            target: prod
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        ports:
            - "8002:8002"
        env_file:
            - .env
        restart: on-failure
        command: node main.js

    rabbitmq:
        image: rabbitmq:3.9.13-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: on-failure
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
