version: '3.8'
services:
    bot:
        container_name: bot
        build:
            context: ./bot
            dockerfile: ./Dockerfile.dev
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        env_file:
            - ./bot/.env
        command: yarn dev
        restart: always
        volumes:
            - ./bot:/app

    api:
        container_name: api
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        depends_on:
            - rabbitmq
        links:
            - rabbitmq
        env_file:
            - ./api/.env
        command: yarn dev
        restart: always
        volumes:
            - ./api:/app

    rabbitmq:
        image: rabbitmq:3.9.13-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
